# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: postgresql
  encoding: utf8
  database: database_development
  pool: 5
  timeout: 5000
  username: postgres
  password: aalr615v
  host: 127.0.0.1

test: &TEST
  adapter: postgres
  encoding: utf8
  database: project_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5