# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


PUNS=
[
"I'm reading a book about anti-gravity. It's impossible to put down!",
"A cross-eyed teacher couldn’t control his pupils",
"A mean crook going down stairs = A condescending con, descending",
"A police officer just knocked on my door and told me my dogs are chasing people on bikes. That’s ridiculous. My dogs don’t even own bikes",
"All chemists know that alcohol is always a solution",
"Becoming a vegetarian is a big missed steak.",
"Boy, I just got hit in the head with a can of soda. I was lucky it was a soft drink.",
"Coffee has a rough time in our house. It gets mugged every single morning!",
"Did you hear about that cheese factory that exploded in France? There was nothing left but de Brie!",
"Did you hear about the guy whose whole left side was cut off? He’s all right now",
"Did you hear about the Italian chef with a terminal illness? He pastaway.",
"Did you see the movie about the hot dog? It was an Oscar wiener.",
"England doesn't have a kidney bank, but it does have a Liverpool",
"German sausage jokes are just the wurst",
"Hal: How did you get hit on the head with a book? Sal: I only have my shelf to blame.",
"hat do you get when you mix alcohol and literature? Tequila mockingbird",
"He who laughs last thinks slowest",
"Hear about the new restaurant called Karma? There’s no menu - you get what you deserve",
"How did the picture end up in jail? It was framed!",
"How do you make holy water? You boil the hell out of it",
"How does an attorney sleep? First he lies on one side, then he lies on the other",
"How does Moses make coffee? Hebrews it",
"How was Rome split in two? With a pair of Ceasars",
"I asked a Frenchman if he played video games. He said Wii!",
"I bought a boat because it was for sail",
"I can’t believe I got fired from the calendar factory. All I did was take a day off",
"I don't suffer from insanity. I enjoy every minute of it",
"I hate how funerals are always at 9 a.m. I’m not really a mourning person",
"I have a few jokes about unemployed people, but none of them work",
"'I have a split personality,' said Tom, being frank.",
"I just found out that I'm color blind. The news came completely out of the green!",
"I lost my job at the bank on my very first day. A woman asked me to check her balance, so I pushed her over",
"I lost my mood ring, and I don't know how I'm feeling about that",
"I love when candy canes are in mint condition.",
"I love you from my head tomatoes",
"I once met a pig that did karate…we called him Pork Chop!",
"I Renamed my iPod The Titanic, so when I plug it in, it says 'The Titanic is syncing.'",
"I saw an ad for burial plots, and I thought: 'That’s the last thing I need!'",
"I tried to sue the airline for losing my luggage. I lost my case",
"I used to be indecisive; now I'm not so sure",
"I used to go fishing with Skrillex. But he kept dropping the bass!",
"I walked into my sister's room and tripped on a bra... It was a booby trap",
"I was going to make a chemistry joke, but since I'm kinda late to the thread, the good ones argon",
"I was told baloons are terrified of Pop Music",
"I was wondering why the ball was getting bigger. Then it hit me",
"I wasn’t originally going to get a brain transplant, but then I changed my mind",
"I went to a seafood restaurant and slipped. I pulled a mussel.",
"I went to buy some camouflage trousers yesterday but couldn't find any",
"If you were a fruit, you'd be a fine-apple",
"I'm not a doctor but I'm losing my patience",
"I'm on a seafood diet. Every time I see food, I eat it",
"Is it ignorance or apathy that's destroying the world today? I don't know and don't really care",
"It was an emotional wedding. Even the cake was in tiers.",
"It's hard to explain puns to kleptomaniacs because they always take things literally",
"Jill broke her finger today, but on the other hand she was completely fine",
"Last night, I dreamed I was swimming in an ocean of orange soda. But it was just a Fanta sea",
"Let me tell you about my grandfather. He was a good man, a brave man. He had the heart of a lion, and a lifetime ban from the zoo",
"Light travels faster than sound. That's why some people appear bright until you hear them speak",
"My buddy said he threw a stick five miles and his dog managed to find it and brought it back. Seems a little far fetched.",
"My dad farted in an elevator, it was wrong on so many levels",
"My dad, unfortunately, passed away when we couldn’t remember his blood type… His last words to us were, 'Be positive!'",
"My ex-wife still misses me. But her aim is starting to improve!",
"My ex-wife still misses me. But her aim is starting to improve",
"My girlfriend thought I'd never be able to make a car out of spaghetti… You should've seen her face when I drove pasta!",
"My parents said I can't drink coffee anymore. Or else they'll ground me!",
"My wife refuses to go to a nude beach with me…I think she's just being clothes-minded!",
"Need an ark? I Noah guy",
"One lung said to another…we be-lung together!",
"Police were called to a daycare center where a three-year-old was resisting a rest",
"Q. What did one blade of grass say to another about the lack of rain? A. I guess we'll just have to make dew.",
"Q. What do you call a fake noodle? A. An impasta.",
"Q. Which type of vegetable tries to be cool, but is only partly successful at it? A. The radish.",
"Q: How do you organize a space party? A: You planet",
"Q: How do you put a baby alien to sleep? A: You rocket",
"Q: What did the volcano say to his wife? A: I lava you",
"Q: What do you call a classy fish? A: Sofishticated",
"Q: What do you call a dog magician? A: A Labrabacadabrador",
"Q: What do you call and alligator in a vest? A: An investigator",
"Q: What do you call the king of vegetables? A: Elvis Parsley.",
"Q: What do you get when you play Tug-of-War with a pig? A: Pulled-Pork.",
"Q: What happened to the guy who sued over his missing luggage? A: He lost his case.",
"She had a photographic memory but never developed it",
"Sleeping comes so naturally to me, I could do it with my eyes closed",
"Somebody stole all my lamps… I couldn’t be more de-lighted!",
"Somebody stole all my lamps….and I couldn't be more de-lighted!",
"Spending a lot of time at the coffee bar can cause a latte problems.",
"Sure, I drink brake fluid. But I can stop anytime!",
"The furniture store keeps calling me to come back. But all I wanted was one night stand",
"The guy who invented the door knocker got a no-bell prize",
"The machine at the coin factory just suddenly stopped working, with no explanation. It doesn’t make any cents",
"The majority of Americans find bananas a peeling.",
"The man who survived pepper spray and mustard gas is now a seasoned veteran",
"The other day I tried to make a chemistry joke, but got no reaction",
"The past, the present, and the future walk into a bar. It was tense!",
"The quickest way to make antifreeze? Just steal her blanket!",
"There was a kidnapping at school yesterday. Don’t worry, though - he woke up",
"Two fish are in a tank, one says to the other 'how do you drive this thing?'",
"Two windmills are standing in a wind farm. One asks, 'What’s your favorite kind of music?' The other says, 'I’m a big metal fan.'",
"What are the strongest days of the week? Saturday and Sunday, the rest are weekdays",
"What did one flag say to the other? Nothing, it just waved.",
"What did syrup to the waffle? I love you a waffle lot!",
"What did the duck say when she purchased new lipstick? Put it on my bill!",
"What did the grape say when it got stepped on? Nothing - but it let out a little whine",
"What did the hamburger name it's baby? Patty!",
"What did the janitor say when he jumped out of the closet? SUPPLIES!",
"What did the sushi say to the bee? Wasabee!",
"What do you call a bee that can’t make up its mind? A maybe",
"What do you call a bee that can't make up its mind? A Maybe",
"What do you call a man with no arms and no legs stuffed in your mailbox? Bill",
"What do you call a pig that does karate? Pork chop",
"What do you call a super articulate dinosaur? A Thesaurus",
"What do you call a thieving alligator? A Crookodile",
"What do you call the ghost of a chicken? A poultry-geist",
"What do you call the wife of a hippie? A Mississippi!",
"What do you call the wife of a hippie? A Mississippi",
"What do you do with chemists when they die? Barium!",
"What does a grape say when it gets stepped on? Nothing, it just lets out a little wine.",
"What is the musical part of a snake? The scales.",
"What should a lawyer always wear to a court? A good lawsuit!",
"What washes up on tiny beaches? Microwaves",
"What would you get if you'd put a lawyer in a suit? A lawsuit",
"What’s the difference between a hippo and a zippo? One is really heavy and the other is a little lighter",
"What’s the difference between a poorly dressed man on a bicycle and a nicely dressed man on a tricycle? A tire",
"What's the difference between a hippo and a zippo? One is really heavy and the other is a little lighter!",
"When everything is coming your way, you're in the wrong lane",
"When life gives you melons, you're dyslexic",
"When the past, present, and future go camping they always argue. It's intense tense in tents",
"Whenever I undress in the bathroom… My shower gets turned on!",
"Which country’s capital has the fastest-growing population? Ireland. Every day it’s Dublin.",
"Who is the penguin's favorite Aunt? Aunt-Arctica!",
"Why are frogs so happy? They eat whatever bugs them",
"Why aren’t dogs good dancers? Because they have two left feet!",
"Why didn't the cat go to the vet? He was feline fine!",
"Why is the number six afraid of seven? Because seven ate nine",
"Why was the baby ant confused? Because all his uncles were ants!",
"Why was the cookie sad? Because his mom was a wafer long!",
"Will glass coffins be a success? Remains to be seen",
"You really shouldn't be intimidated by advanced math…it's easy as pi!"
]



ITERATOR = 0

for pun in PUNS
    p = Pun.create(tweet: pun, publication_date: Date.today + ITERATOR)
    ITERATOR += 1
    print "/////////////////////////////////////////////////////////////"
    print p.tweet
    print p.publication_date
    print ITERATOR
    print "/////////////////////////////////////////////////////////////"
end